export const AUTH_REQ="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILUE";

export const FETCH_POSTS=" FETCH_POSTS";
export const CREATE_POST="CREATE_POST";
export const UPDATE_POST=" UPDATE_POST";
export const DELETE_POST="DELETE_POST";
export const FETCH_PAGED_POSTS="FETCH_PAGED_POSTS";
export const FETCH_PAGED_POSTS_KEYWORD="FETCH_PAGED_POSTS_KEYWORD";
export const FETCH_TOTAL_POSTS="FETCH_TOTAL_POSTS";

export const FETCH_COMMENTS=" FETCH_COMMENTS";
export const FETCH_PAGED_COMMENTS="FETCH_PAGED_COMMENTS";
export const CREATE_COMMENT="CREATE_COMMENT";
export const UPDATE_COMMENT=" UPDATE_COMMENT";
export const DELETE_COMMENT="DELETE_COMMENT";

export const SEARCH_REQUEST="SEARCH_REQUEST";